### ISSUE TITLE
Space key suggestion bug

### ISSUE THREAD

**Issue by coeyes** [mark-wiemer-org/ahkpp#110]
## Description

In vscode autohotkey-plus-plus,
just pushing space key suggest code completion.
this is very annoying to edit code.
In other language mode (ie: javascript), suggestion only activated when pushing non-space key or ctrl + space key.

## Reproduction steps

1. open any ahk file.
2. push space

## Expected behavior
1.  just pushing space should not activated suggestion.

**Comment by mark-wiemer** [comment]
on track for closure :)
