### ISSUE TITLE
#hotif not showing

### ISSUE THREAD

**Issue by Hungermanw3t** [mark-wiemer-org/ahkpp#116]
## Description

i'm not sure why but #hotif isn't showing up in the predictions and isn't being recognised

## Reproduction steps

1. type #hotif
2. its not recognised

## Expected behavior

its an official feature of ahk so it would be nice for it to be part of the extension
https://lexikos.github.io/v2/docs/commands/_HotIf.htm

**Comment by mark-wiemer** [comment]
Ah, this is only in AHK v2, which isn't currently supported (ref #96). Let me see what I can do to add it with a "v2 only" warning, otherwise this issue may get deprioritized :(

**Comment by mark-wiemer** [comment]
We'll need to look at how the formatter works with this code, and whether it's worth adding v2-specific logic here

**Comment by mark-wiemer** [comment]
Closing this as a duplicate of #96
