### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [mark-wiemer-org/ahkpp#152]
The [Open VSX Registry](https://open-vsx.org/?search=autohotkey) currently only has the AHK Plus extension published by its author (so that was at least maintained 2 years ago).
Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia. It would be nice to have this extension be directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions, which also drops a link to https://github.com/HaaLeo/publish-vscode-extension#readme - a GitHub action that can publish to both marketplaces (if you want to automate it like "just create a release and get it published"), but that's optional.

**Comment by mark-wiemer** [comment]
For reference: [automated publishing guide](https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing)

**Comment by mark-wiemer** [comment]
I am not alone in my token frustration: https://github.com/microsoft/vsmarketplace/discussions/161

**Comment by GitMensch** [comment]
Just out of interest: Does it get any better when using https://github.com/HaaLeo/publish-vscode-extension#readme for the automated publishing or is getting that token in a working state the main issue?

**Comment by mark-wiemer** [comment]
I would split this work into two categories:

1. First-time setup (creating accounts, creating tokens, registering namespaces, publishing app for the first time)
2. Recurring work (setting up workflows to publish automatically, streamlining those workflows)

On count 1, Visual Studio Marketplace has been a nightmare, where Open VSX has been a relatively normal experience, much closer to "just working".

On count 2, the automated publishing GitHub action you shared will make my life easier. It'd be nice if git / GitHub made it easier to generate tags, attach releases to them, and extract the titles and descriptions from `Changelog.md`, but I'll survive :)

I've almost got https://github.com/mark-wiemer/vscode-helloworld set up :)

**Comment by mark-wiemer** [comment]
See https://github.com/EclipseFdn/open-vsx.org/issues/1114

**Comment by mark-wiemer** [comment]
Published HelloWorld on Open VSX :) https://open-vsx.org/extension/mark-wiemer/helloworld-2022

**Comment by mark-wiemer** [comment]
https://github.com/mark-wiemer/vscode-helloworld/pull/38

**Comment by GitMensch** [comment]
That's a useful repo to point to - thanks!

**Comment by GitMensch** [comment]
> It'd be nice if git / GitHub made it easier to generate tags, attach releases to them, and extract the titles and descriptions from `Changelog.md`, but I'll survive :)

I see you've partially tackled this but you may want to have a look at a "full setup" (much more complicated as it - at least when looking the last time - tries to also create the Changelog/NEWS, not "just take it", but the simplified version may be what you aim for) https://github.com/westes/flex/pull/480

**Comment by mark-wiemer** [comment]
Created https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/156 for that fancier work 😄

**Comment by mark-wiemer** [comment]
Unfortunately due to my frantic fix for https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/153, the repo is in a bad state in terms of automatic deployments. First priority is now "re-deploy 2.8.3 as 2.8.5 from main with necessary bugfixes", which will probably take a bit. I'm on vacation next week, so don't expect this until July 18 at the earliest. Sorry for the delay :(

**Comment by GitMensch** [comment]
I'm not in a hurry 😄, mainly got here by your deprecation post...

**Comment by mark-wiemer** [comment]
@GitMensch published 2.8.5 manually :)

[AHK++ on Open VSX](https://open-vsx.org/extension/mark-wiemer/vscode-autohotkey-plus-plus)

**Comment by mark-wiemer** [comment]
![Screenshot_20220720-003758](https://user-images.githubusercontent.com/7833360/179924745-ac31a87e-affa-4a2c-be8b-53821be6caf8.jpg)

I'm not sure what you mean, I'm seeing it at the link I provided. Can you add some more details?

**Comment by GitMensch** [comment]
> I'm not sure what you mean, I'm seeing it at the link I provided. Can you add some more details?

Open VSX is fine - and therefore the issue can be closed; but on GH releases there is only a 2.8.5 pre-release so far.

**Comment by mark-wiemer** [comment]
Ah, yes, I'd like to leave it that way. In all honesty, I should've just published 2.8.4 on OVSX, but it's too late. I don't think I can unpublish 2.8.5. My mistake.

I'm assuming OVSX is much smaller than Visual Studio Marketplace, and I'm confident enough in the release that 2.8.5 won't be as terrible as 2.8.3

If something is wrong, please let me know right away.

But I'm still not comfortable saying 2.8.5 is ready for general availability on VS Marketplace or GitHub. I'd like to give it a week total in pre-release mode before I move it to a regular release, if that's OK.

**Comment by GitMensch** [comment]
Sure. Still closing this as solve now :-)

**Comment by fgimian** [comment]
@mark-wiemer Sorry to comment on a closed issue, but I noticed the version on OpenVSX is currently older than the one on the VS marketplace. Any chance you could publish an update when you have a free moment?

Thanks heaps
Fotis

**Comment by mark-wiemer** [comment]
Re-opened, I'll validate the publishing flow soon (~1 month max, busy times ahead, sorry!)

**Comment by mark-wiemer** [comment]
@fgimian everything looks good to me, can you clarify what's missing?

![image](https://github.com/user-attachments/assets/ec9d464b-270f-41e0-b7a4-e5b045439c14)

**Comment by fgimian** [comment]
> @fgimian everything looks good to me, can you clarify what's missing?
> 
> https://open-vsx.org/extension/mark-wiemer/vscode-autohotkey-plus-plus
> 
> ![image](https://private-user-images.githubusercontent.com/7833360/362041139-ec9d464b-270f-41e0-b7a4-e5b045439c14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDM3MTYsIm5iZiI6MTcyNDg0MzQxNiwicGF0aCI6Ii83ODMzMzYwLzM2MjA0MTEzOS1lYzlkNDY0Yi0yNzBmLTQxZTAtYjdhNC1lNWIwNDU0MzljMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTExMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI4NzhkMWY5ZjQ4NDE4NjI5ZTUyY2E3OGIxM2YzODQ2NGU3NTY3MDQ3MGI3ZjQwZWYzNzA4MTZhOTliZTc4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FmtvMlr3ONemPR2RPmq-hHYQRoGdrsJ-0DtSe00BYxo)

Apologies, I suspect the reason I wasn't seeing it is that 5.1.x versions are pre-release versions.

Thank you so much
Fotis
