### ISSUE TITLE
Windows 7 not supported by default

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer-org/ahkpp#238]
Today another problem arrive :( Microsoft stops support VS Code for Windows 7. Last working version is 1.70.3. Now test suite downloads 1.71.0 and fails to run tests.

Solution: explicitly pass VS Code executable path to `runTests()` in `.\src\test\runTest.ts`

```ts
runTests({
    vscodeExecutablePath: './.vscode-test/vscode-win32-archive-1.70.3/Code.exe',
    ...
```

Can we somehow workaround this problem (do not mess with modified file in Git)?

_Originally posted by @kyklish in https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/discussions/220#discussioncomment-3562197_

**Comment by kyklish** [comment]
Another ugly workaround is rename `vscode-win32-archive-1.70.3` folder to most recent version (for example `vscode-win32-archive-1.71.0`) and tests will skip download recent version, tests will run.

**Comment by mark-wiemer** [comment]
Closing as not a priority--I'd encourage anyone still using Windows 7 to upgrade, it's no longer supported and almost certainly vulnerable to hacking.
