### ISSUE TITLE
Extension activation fails on tests

### ISSUE THREAD

**Issue by kyklish** [mark-wiemer-org/ahkpp#305]
## Description

1. Switch branch.
1. Launch `Test Extension`.
1. See error notification.
1. Sometimes console got stuck with infinite progress icon.
1. After it launch `Launch Extension` got same error (not always), formatter not work.

Workaround: terminate tasks in console, re-run `npm run dev`.

![FailExtensionActivate](https://user-images.githubusercontent.com/964801/209533631-73e4df7d-efe6-413a-8443-d9d767927f0c.png)

`npm i` command says `up to date`

## Additional errors

![Code_15-23-27-655_REKY](https://user-images.githubusercontent.com/964801/211021301-52793126-4718-4234-9192-6089822d3ca2.png)

Build succeed, but extension does not activate and not work.

**Comment by mark-wiemer** [comment]
@kyklish are you still encountering this issue after updating all your branches? It seems like a problem with one branch having old names and the main branch having new names. Typically, background tasks are bad at recognizing when git switches branches / lots of files are changed simultaneously.

I'm not able to reproduce the issue, could you record your screen and share a GIF? [ShareX](https://getsharex.com/) is a great tool for that.

**Comment by mark-wiemer** [comment]
Updated tsconfig.json recently, this should be resolved. @kyklish please re-open if you're still having issues.
