### ISSUE TITLE
Strange behavior while moving code using built-in indentation rules in VS Code

### ISSUE THREAD

**Issue by kyklish** [mark-wiemer-org/ahkpp#319]
## Description

Strange behavior while moving code using built-in indentation rules in VS Code `.\language\ahk.configuration.json` parameter `indentNextLinePattern`.

![Example](https://user-images.githubusercontent.com/964801/209550885-f660c9ee-60ea-4406-add4-0fe0894e30bb.gif)

## Possible wrong state while moving `var`

```ahk
if (expr)
    var
    code
```

**Comment by mark-wiemer** [comment]
Hey, this may be related to the comments. I'm not able to repro the issue with this snippet, are you?

```
var
foo() {
    if expression
        code
    code
    if (expression)
        code
    if (expression) {
        code
    }
    
}
```

**Comment by kyklish** [comment]
Now I see strange behavior in both directions :)

## Initial
```ahk
var
if (expr)
    code
code
```

## Expected
```ahk
if (expr)
    var
code
code
```

## Actual
```ahk
if (expr)
    var
    code
code
```

**Comment by mark-wiemer** [comment]
Closing this as very low impact, I see the same behavior with JS/TS but a quick format resolves the issue :)
