### ISSUE TITLE
3.3.1 breaks the debugger

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer-org/ahkpp#369]
Output to console when using the debugger...

`2023-06-21T10:27:46.897Z o.hasOwnProperty is not a function`

**Comment by mark-wiemer** [comment]
Thank you for reporting this. I'm sorry I didn't test this further, I'm yanking the release now and putting out 3.3.2 to ensure everyone gets back to a working state. I was irresponsible to release without comprehensive manual tests, and I'm sorry for the inconvenience.

**Comment by mark-wiemer** [comment]
- Validated that the code is equivalent to 3.3.0 via `git diff HEAD v3.3.0`.
- Manually ensured debugger still hits breakpoint on simple script
- Released 3.3.2, should be validated within 5 minutes.
