### ISSUE TITLE
[v2] Can't debug from VS Code debug menu

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer-org/ahkpp#385]
**Is your issue related to a problem? Please describe.**
Can't debug using VS Code debug menu

**Describe the solution you'd like**
When I go to the "Run and Debug" view, I should be able to select "AutoHotkey v2 Debugger" and run it on my v2 files.

**Describe alternatives you've considered**
I click the custom debug button in the title bar or use the debug command

**Comment by slishnevsky** [comment]
I wanted to use AutoHotkey Extension for Visual Studio Code to write, debug and run AHK v2 scripts.

I installed AutoHotkey v2 as usual, to c:\Program Files\AutoHotkey\


[![enter image description here][1]][1]

Then, I installed the extension with default configuration pointing correctly to the AutoHotkey installation files

[![enter image description here][2]][2]

[![enter image description here][3]][3]

Then, I created a simple test.ahk file

[![enter image description here][4]][4]

So, when I want to run it in a Debug mode, I press Ctrl+Alt+F9 (as defined in the configuration), but nothing happens, the breakpoint is not being hit at all.

Any idea why?

Thank you.


  [1]: https://i.stack.imgur.com/HeapO.png
  [2]: https://i.stack.imgur.com/6zfKb.png
  [3]: https://i.stack.imgur.com/xdIu3.png
  [4]: https://i.stack.imgur.com/qhxZ6.png

**Comment by MystK** [comment]
For others that stumbled onto this page with the similar issue, [vscode-autohotkey-debug](https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug) works for v2.

**Comment by mark-wiemer** [comment]
Cutting this for now, the custom debug button added to the title menu is sufficient. Going to focus on other features first and I can revisit this if folks ask for it.
