### ISSUE TITLE
Run script as ahk v1

### ISSUE THREAD

**Issue by Sperhak323** [mark-wiemer-org/ahkpp#391]
How to run script as ahk v1? I cannot find any button or something. 
When i try run script with ctrl+F9 I get error from ahk because run it in v2 and i have script in v1
Thanks for reply.

**Comment by mark-wiemer** [comment]
Hi @Sperhak323, please check out these settings:

1. The language mode is set to AHK v1 (you can use F1 to bring up the command palette, then search "Change Language Mode")
2. The path to the v1 interpreter in the settings is correct

If you're still struggling, please paste a small script you're trying to run and some screenshots of your settings so I can assist further.

**Comment by Sperhak323** [comment]
Thanks, first step works.

**Comment by helperman** [comment]
How to set AHK V1 for newly opened ahk-files by default?

**Comment by fade2gray** [comment]
@mark-wiemer
> The language mode is set to AHK v1...
I've noticed, if you create a new empty text file in explorer with an ahk extension and use the context menu to open it with VSCode, the file will be opened by default in v2 mode.

**Comment by mark-wiemer** [comment]
Yep @fade2gray, somehow it's defaulting to AHK v2 even though I don't want it to :/ I'm at work rn, feel free to open a bug for that but you should be able to change the default language association for `.ahk` files to AHK v1 :)

**Comment by helperman** [comment]
By the way, do you know any way to automatically convert ahk-script from v1 to v2?
It's qute tedious to do it manually.

**Comment by fade2gray** [comment]
https://github.com/mmikeww/AHK-v2-script-converter is a help but won't do it all for you.

**Comment by helperman** [comment]
@fade2gray  how good it is when there are people like you in the world who will help when it's needed.
I've just found the solution that's why I deleted my post.

**Comment by hubisan** [comment]
It is possible to set the default language for a file extension[^1].

Add this to your settings file to associate .ahk with ahk v1:

```
  "files.associations": {
      "*.ahk": "ahk"
  }
```

Use "ahk2" for ahk v2.

You can also associate specific folders to a certain language[^2]:

```
"files.associations": {
    "**/somefolder/*.*": "ahk",
    "**/otherfolder/*.*": "ahk2"
}
```
A glob pattern[^3] is used for file matching.

[^1]: https://code.visualstudio.com/docs/languages/overview#_add-a-file-extension-to-a-language
[^2]: https://code.visualstudio.com/docs/languages/overview#_can-i-map-additional-file-extensions-to-a-language
[^3]: https://code.visualstudio.com/docs/editor/glob-patterns

**Comment by fade2gray** [comment]
I find that using `.ah1` and `.ah2` extensions just work out-of-the-box.
