### ISSUE TITLE
Extension forgot AHK location

### ISSUE THREAD

**Issue by Terrimar** [mark-wiemer-org/ahkpp#399]
I installed AHK and the AHK++ extension a year ago and have not used it for anything other than to run a simple script nearly every day.  Yesterday it was running, today it reports

> 2023-08-18T23:48:07.259Z AutoHotkey execute bin not found: C:/Program Files/AutoHotkey/v2/AutoHotkey64.exe

The extension settings do indeed show:
> Ahk++ › File: Compiler Path
Path to the AHK compiler. (This is the same for both v1 and v2.)
C:/Program Files/AutoHotkey/Compiler/Ahk2Exe.exe

The problem is that my AHK is installed single user under `AppData\Local\AutoHotKey`.  I can fix the extension settings of course, but is there a known issue with the extension reverting to the default bin location for no reason?  The extension is AHK++ Version 5.0.2, apparently kept up to date by VSCode, but I don't know if 5.0.2 was installed between yesterday and today.

**Comment by fade2gray** [comment]
When clicking on the AHK++ settings cogwheel, you see the option to `Install Another Version` - you could try winding back to 5.0.1 or earlier.

**Comment by Terrimar** [comment]
5.0.2 works fine after I put the locations of the AHK v1 files into the v2 settings (leaving them blank didn't work).   I'm just wondered if changing the existing settings was expected behavior for 5.0.2, and if so, if it could be highlighted better.  Seems like a gotcha for a patch release, if that's how it happened.

**Comment by fade2gray** [comment]
5.0.0, 5.0.1 and 5.02 were all [released](https://github.com/mark-wiemer-org/ahkpp/commits/main) in quick succession. At some point, I had to install the latest version of AutoHotkey v2, and adjust the v1/v2 executable paths in AHK++ settings - can't remember at what point though, but I don't particularly recall encountering the error that you did.

**Comment by mark-wiemer** [comment]
Yes, when the name of the settings changed from "compile path" to "compiler path", that reset the settings. You can view the old settings in settings.json via the command palette, and then update the keys to match the new keys. This was noted in the 5.0.0 change log. Please let me know if you have any questions!

**Comment by frank-hank** [comment]
> 将 AHK v1 文件的位置放入 v2 设置后（将其留空不起作用），5.0.2 工作正常。我只是想知道更改现有设置是否是 5.0.2 的预期行为，如果是，是否可以更好地突出显示。看起来像是补丁发布的陷阱，如果事情是这样发生的话。

it work!!!!
