### ISSUE TITLE
AHK++ is not activating.

### ISSUE THREAD

**Issue by dDeepLb** [mark-wiemer-org/ahkpp#405]
## Description

When I open VS Code, in AHK++ Runtime Status I see "Not yet activated."
At installation it worked, but now no.
Therefore I can't run scripts with hotkey.

## Reproduction steps

1. Go to folder with VS Code
2. Double-click on VS Code
3. Open AHK++ Ext Page > Runtime Status

## Expected behavior

Well... I think it should load AHK++

**Comment by mark-wiemer** [comment]
Can you paste the error?

**Comment by mark-wiemer** [comment]
@dDeepLb have you opened an AHK file? The extension only activates once it's needed :)

**Comment by dDeepLb** [comment]
Yes, opened one before VS Code launch and second when Code was already opened. AHK++ still not activated..

**Comment by fade2gray** [comment]
> The extension only activates once it's needed :)

This piqued my curiosity. I have VSCode installed on a VM, so I uninstalled it along with the `.vscode` and `Code` folders, and reinstalled it (basically a clean install). I then (without opening any AHK scripts) installed AutoHokey Plus Plus and nothing else - et voilà, instant activation.

**Comment by dDeepLb** [comment]
Yes, it activated on instalation. But after I re-entered VS Code - no activation..

**Comment by fade2gray** [comment]
Perhaps @mark-wiemer can explain a little more.

**Comment by mark-wiemer** [comment]
Unfortunately I really don't have ideas here. Of you uninstall and reinstall does it start failing again? VS Code actually recommended we extension devs remove some extension activation triggers as they claimed to handle activation themselves, clearly that's not working.

**Comment by dDeepLb** [comment]
Even after I reinstalled it nothing new... Highlighting is here, but IntelliSense not... Maybe there is some way to activate it through dev tools or so?

**Comment by mark-wiemer** [comment]
Can you try executing AHK commands? e.g. pressing Ctrl+F1 to open quick help? Or opening a `.ahk` file, opening command palette (F1), then typing "ahk++" and selecting any of the results?

Really sorry you're experiencing this, but I currently have no way to reproduce the issue. I will try to read developer documentation around this and look around to see if other extensions have experienced this before.

**Comment by dDeepLb** [comment]
It didn't work. So I completely reinstalled it by deleting AHK++ folder in `C:\Users\myUsername\.vscode\extensions`, then reinstalled it in VS Code, restarted. 
It wouldn't load... Until I created a new file with the .ahk extension. 

Yes, it is now fully functional and shows me: 
``` 
Activation event: onLanguage:ahk2 
Activation time: 103ms 
``` 
in working state. 
Now it works even when I open files with .ahk extension, which it didn't before.
