### ISSUE TITLE
Formatter replaces multiple spaces with a single space inside a string

### ISSUE THREAD

**Issue by hubisan** [mark-wiemer-org/ahkpp#411]
### Description

The formatter shouldn't replaces multiple spaces with a single space inside strings enclosed with quotations marks.

### Snippet before formatting

```autohotkey
string_with_multiple_spaces := "  "
string_with_multiple_spaces_2 := " ahk   is    nice   "
```

### Expected formatted output snippet

Multiple spaces inside a string should be preserved:

```autohotkey
string_with_multiple_spaces := "  "
string_with_multiple_spaces_2 := " ahk   is    nice   "
```

### Actual formatted output snippet

Multiple spaces are replaced with a single space:

```autohotkey
string_with_multiple_spaces := " "
string_with_multiple_spaces_2 := " ahk is nice "
```

**Comment by mark-wiemer** [comment]
This is the `Trim Extra Spaces` setting, you can turn it off and it should be off by default for this reason--thanks for reporting this! Leaving this bug open until I write some code again, should be a very easy fix :)

Ctrl + comma to open settings, then find this one and toggle it off:

![image](https://github.com/mark-wiemer-org/ahkpp/assets/7833360/7b65c1d9-4e66-4bac-925f-a0b963c7c92a)

**Comment by mark-wiemer** [comment]
Because this is a bug, fixing this is not a semver-major change. Going to go ahead with this now

**Comment by mark-wiemer** [comment]
Ref #189 and #191. This bug was introduced in AHK++ 3.0.0
