### ISSUE TITLE
Wrong indentation on copy-paste

### ISSUE THREAD

**Issue by helperman** [mark-wiemer-org/ahkpp#412]
## Description

I like to indent code of each separate hotkey in AHK-script.
It makes code more readable and clean.
The issue is when after copy-pasting a code with indentation the pasted code looses this indentation.

## Reproduction steps

![0000000735](https://github.com/mark-wiemer-org/ahkpp/assets/8351863/78c15351-b344-40a0-bffd-ed2df604fbee)

## Expected behavior

Indentation is the same as in a copied text.

## Actual behavior
There is no indentation in a copied text.

**Comment by mark-wiemer** [comment]
What happens when you run `Format Document` (Shift+Alt+F)? The document should look nice and indented:

![Code_-_Insiders_g2mZYqbBFf](https://github.com/mark-wiemer-org/ahkpp/assets/7833360/6d669340-54d7-4530-b08a-cfc7bef25d62)

**Comment by helperman** [comment]
Yes, Shift+Alt+F fixes indentation. 
Therefore, the issue is pasting, not formatting.

**Comment by mark-wiemer** [comment]
Pasting is out of scope of this extension, maybe you have some other setting messing things up? Does this issue occur when you disable this extension and try to reproduce the issue?

**Comment by fade2gray** [comment]
I also find this frustrating, that the indentation, included in the copied code is removed when pasted after a hotkey or label, but I do find that if you perform an 'undo' `Ctrl+Z` immediately after pasting, the indentation will be restored.

Note: `Indent Code After Label` doesn't appear to work - is this related?

**Comment by kyklish** [comment]
> Note: `Indent Code After Label` in the settings doesn't appear to work - is this related?
This setting was introduced for old formatter (when you hit Alt+Shift+F hotkey), it will format whole file, it didn't work with selected or pasted text.

**Comment by kyklish** [comment]
Removing [this](https://github.com/mark-wiemer-org/ahkpp/blob/main/language/ahk.configuration.json#L23-L26) lines may fix this behavior.
