### ISSUE TITLE
No format intelicence or formating or colors

### ISSUE THREAD

**Issue by neondeex** [mark-wiemer-org/ahkpp#414]
## Description

I installed the extension and reopen vs code and is not working 

## Reproduction steps

1 install
2 do not work

## Expected behavior

to work

## Additional context

i don't know if i need something else

**Comment by asheroto** [comment]
Same issue here. Have used this excellent extension or a long time but recently it broke.

![image](https://github.com/mark-wiemer-org/ahkpp/assets/49938263/e25f6dd0-9b9e-4d78-9696-8eb719a00643)

Using AHK v1 script, file extension is `.lnk`.

**Comment by mark-wiemer** [comment]
Hmm, I'll post some updated steps for how to do a full uninstall and re-install, a few folks have reported issues like this. Give me a few days though, life remains busy :/

**Comment by asheroto** [comment]
Thanks. I did try to uninstall and reinstall the extension. Maybe there's a debug log somewhere I could help diagnose with.

**Comment by mark-wiemer** [comment]
There are some special locations where VS Code keeps a copy of all extensions, even after you uninstall them. I find those locations using the ["Everything" search engine](https://www.voidtools.com/support/everything). Looks like it's under `C:\Users\%user%\.vscode\extensions\mark-wiemer.vscode-autohotkey-plus-plus-5.0.3` by default, try removing that folder entirely and then uninstalling.

Note that your settings will be preserved as they're stored in `C:\Users\%user%\AppData\Roaming\Code\User\settings.json` :) (note this folder is hidden in File Explorer by default)

Hope this helps, see also #396 for more advice.
