### ISSUE TITLE
The Open AutoHotkey Help command is failing

### ISSUE THREAD

**Issue by angelgil** [mark-wiemer-org/ahkpp#420]
## Description

In an AHK Script V2, whenever I press Ctrl + F1 in a statement, VS Code shows up the following error:

A Command failed:
"C:\Users\YYYYYY\AutoHotkey\AutoHotkeyU64.exe"
/ErrorStdOut **(2):==> Call to nonexistent function.
Specifically: SetWinDelay(IO)

## Reproduction steps

1. Go to 'VS Code'.
2. Open an AHK v2 script.
3. Put the cursor in statement, for instance, Send.
4. Press Ctrl + F1 to call the AutoHotkey Help.
5. VS Code shows up the error.

## Expected behavior

The extension should open the AutoHotkey help document.

## Additional context

![Extension version](https://github.com/mark-wiemer-org/ahkpp/assets/930727/06f75278-e538-43ed-828b-9c199296f51d)
![Video of the issue](https://github.com/mark-wiemer-org/ahkpp/assets/930727/2203e5d8-f58c-4193-ae76-6e4379362d71)

**Comment by fade2gray** [comment]
You may need to edit your paths in the extension's settings.

![Screenshot 2024-02-16 184023](https://github.com/mark-wiemer-org/ahkpp/assets/1332009/2bb82fab-8d01-48ad-83f8-19e914bbcc56)

**Comment by angelgil** [comment]
Thanks @fade2gray , I have installed the latest version of AutoHotkey and I have edited the paths as you suggested and now it is working.
