### ISSUE TITLE
Availability as standalone LSP

### ISSUE THREAD

**Issue by pidgeon777** [mark-wiemer-org/ahkpp#423]
This LSP supports AHK v2, and can be run in any editor supporting LSP:

https://github.com/thqby/vscode-autohotkey2-lsp

I was wondering if there is a way to make use of your plugin LSP also, and if yes, how.

I know that with TS/Node.js based LSP (especially in VSCode) you can obtain a `server.js` starting from the TS files, and then with `node server.js --stdio` you can start on LSP.

**Comment by mark-wiemer** [comment]
I'll say there's very little unique LSP code in this repo. Most of it is copied from the credited repos at the bottom of the README and in the changelog. You'll have the best experience just using those directly :) Standalone LSP support for this might be considered if I ever drastically change the logic and fix significant bugs, but it's never something I've deployed before so it'd take some research :)

Don't worry about the project management notification, that's a minor issue I've had that doesn't affect much :)
