### ISSUE TITLE
Shortcut to comment/decomment selected line

### ISSUE THREAD

**Issue by Gharwen** [mark-wiemer-org/ahkpp#425]
In AHK Studio with the shortcut ctrl+j it is possible to toggle a selected command line or block to a comment line/block and vice versa.

Is it possible to implement this in ahk++ ?

This would be a great help, especially when it comes to commenting out larger blocks or "reactivating" commented-out blocks.

**Comment by mark-wiemer** [comment]
@Gharwen, have you tried Ctrl+/ ? That's the default for VS Code :)

**Comment by fade2gray** [comment]
`Shift+Alt+A`?

**Comment by Gharwen** [comment]
In the meantime, I have found the right shortcut.

CTRL+K and CTRL+C for comment a line or marked block
CTRL+K and CTRL+U for uncomment
