### ISSUE TITLE
Debug won't start

### ISSUE THREAD

**Issue by oldbrother8** [mark-wiemer-org/ahkpp#430]
I'm using AHK v1. I love this extension. However, since last few months, the debug won't start sometimes. The break points will be passed without stopping. I reinstalled Visual Code and the extension, but the problem is still there. Please help. Thank you for your great work!

**Comment by fade2gray** [comment]
I think most users of AutoHotkey Plus Plus use the vscode-autohotkey-debug extension.

**Comment by mark-wiemer** [comment]
#396 has instructions for how to do a full uninstall. Even the regular VS Code uninstall keeps a cache, which may cause some issues. However, I do recommend using vscode-autohotkey-debug if you're having issues. I'll keep my eye on this, and if you have repro steps that I can try for troubleshooting, that'd be appreciated :)

**Comment by mark-wiemer** [comment]
Closing as stale
