### ISSUE TITLE
[v2] Can't the v2 version outline be used? Only v1 has an outline?

### ISSUE THREAD

**Issue by oiss** [mark-wiemer-org/ahkpp#431]
![Uploading 微信图片_20240429125744.png…]()
![Uploading 微信图片_20240429125744_1.png…]()

**Is your issue related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mark-wiemer** [comment]
Hi @oiss, sorry for the delay. For now, only the v1 version has an outline, as v2 support is still in preview. Unfortunately, your images failed to upload.
