### ISSUE TITLE
[Pre-release] Global functions (MsgBox, Run) recognized as variables

### ISSUE THREAD

**Issue by H5820121** [mark-wiemer-org/ahkpp#472]
I installed vscode-autohotkey-plus-plus-5.1.0.vsix and I get:
![2024-08-22 205449](https://github.com/user-attachments/assets/b1f0fdf7-ea6f-4480-913e-c6139eafa101)

And when I "Switch to **Release** Version" everything was fine again.
AHKv2

**Comment by mark-wiemer** [comment]
This is a known issue, I'll try to fix it this week :)

**Comment by H5820121** [comment]
Thank you!
I installed the file mark-wiemer.vscode-autohotkey-plus-plus-5.1.0.vsix
55.8 MB
From
https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus
And the issue is resolved.

‫בתאריך יום ו׳, 23 באוג׳ 2024 ב-3:53 מאת ‪Mark Wiemer‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
@Mark Wiemer It's not a issue just a question so I didn't want to start a
new issue:
When I installed AHK++ 5.1.0 I removed AutoHotkey v2 Language Support and I
assume that AHK++ will now be updated in accordance with AutoHotkey v2
Language Support updates, is that true?
I wanted to take this opportunity to thank you personally for your
wonderful extension which is very helpful to me.

‫בתאריך יום ו׳, 23 באוג׳ 2024 ב-3:53 מאת ‪Mark Wiemer‬‏ <‪
***@***.***‬‏>:‬

**Comment by mark-wiemer** [comment]
@H5820121, yes that is the plan. AHK++now includes a submodule that tracks thqby's extension, so all changes there are planned to be incorporated into AHK++. Things may take a bit of extra time as our two branches diverge, but I'm tracking his repo for bugfixes and new features 100% :)
