### ISSUE TITLE
Issue with syntax highlighting when updating or reverting extension

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer-org/ahkpp#481]
Not sure with what version I started noticing this, but it happens with current/prior releases and the pre-releases.

Pre update/revert example:
![SyntaxHighlighting_1](https://github.com/user-attachments/assets/fa06eaf2-09ab-4c0a-9140-ad79607e9cf2)
Post update/revert example
![SyntaxHighlighting_2](https://github.com/user-attachments/assets/70fa8a93-1ded-4b5a-a76b-9699c12d419c)

This can be resolved by formatting the document. If formatting produces any undesired changes to formatting layout, just use Ctrl+Z to undo the formatting, but will retain the correct syntax highlighting.

Also, updating/reverting the extension can cause the 'red conflict underscore' to appear - ~~formatting will also resolve this~~ edit: requires `Developer: Reload Window`.

**Comment by mark-wiemer** [comment]
Can you paste the image text as plaintext as well so I can investigate? The image helps for the colors of course, thank you :)

Can you clarify what steps you're taking? Is this when changing between AHK++ versions / releases? Are there other scenarios that cause this?

**Comment by fade2gray** [comment]
```
global	  gTagChar		:= chr(0x2605)
		, gFuncPtn		:= buildPtn_FUNC()																		; function block (supports nesting)
		, gClassPtn		:= buildPtn_CLS()																		; class	   block (supports nesting)
		, gMQSPtn		:= buildPtn_MStr()																		; v1 multi-line string-block (non expression)
		, gIFPtn		:= buildPtn_IF()																		; 2024-08-06 AMB, ADDED
		, gLblPtn		:= buildPtn_Label()																		; 2024-08-06 AMB, ADDED
		, gHotkeyPtn	:= buildPtn_Hotkey()																	; 2024-08-06 AMB, ADDED
		, gHotStrPtn	:= '^:(?<Opts>[^:]+)*:(?<Trig>[^:]+)::'													; 2024-08-06 AMB, ADDED
		; 2024-07-07 AMB, CHANGED to bypass escaped semicolon
		, gLCPtn		:= '(*UCP)(?m)(?<=\s|)(?<!``);[^\v]*'													; line comment (allows lead ws to be consumed already)
		, gBCPtn		:= '(*UCP)(?m)^\h*(/\*((?>[^*/]+|\*[^/]|/[^*])*)(?>(?-2)(?-1))*(?:\*/|\Z))'				; block comments
		, gQSPtn		:= '(*UCP)(?m)(?:`'`'|`'(?>[^`'\v]+(?:(?<=``)`')?)+`'|""|"(?>[^"\v]+(?:(?<=``)")?)+")'	; quoted string	(UPDATED 2024-06-17)
;		, gBracePtn		:= '(\{(?>[^}{]+|(?-1))*\})'															; nested brace blocks (for future support)
```

**Comment by mark-wiemer** [comment]
Can you clarify what you're doing to update/revert? Is this just going into the Extensions viewlet and installing a different version?

**Comment by fade2gray** [comment]
Yes, it happens when switching between versions. It also happens when using the manual Update option (if one is available) when the Auto Update option is unchecked.

**Comment by mark-wiemer** [comment]
Unfortunately I'll have to close this as out of scope. There is little I can do to reproduce and diagnose issues like this, and if it's fixed by restarting the extension host (F1 > Developer: Restart Extension Host), I'm going to accept that as a sufficient workaround. Do let me know if it troubles you more often, though.
