### ISSUE TITLE
[Pre-release] Changes in ah1 context menu version >= 5.1.2

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer-org/ahkpp#486]
Current release and pre-release 5.1.1
![ah1_ContextMenu_pre](https://github.com/user-attachments/assets/91156776-dfe1-4a84-9523-37d90936a3f0)

Pre-release >= 5.1.2
![ah1_ContextMenu_post](https://github.com/user-attachments/assets/6cbd104a-def4-46ac-98dd-45c067d486b9)

**Comment by mark-wiemer** [comment]
Thanks, I think the only issue is that Run AHK Script is now wayyyyy at the bottom, right? Should be fixed before the full release :)

**Comment by fade2gray** [comment]
> Run AHK Script is now wayyyyy at the bottom

So it is, I missed that - it is greyed out though.

**Comment by mark-wiemer** [comment]
Gotcha, I haven't been paying too close attention to AHK v1, I know how to fix this though. Thanks for reporting it :)

**Comment by fade2gray** [comment]
Just in case you didn't notice in the image, the Run Selection is also greyed out.
