### ISSUE TITLE
Closing brace from arrays moved to next line

### ISSUE THREAD

**Issue by Martin-Milbradt** [mark-wiemer-org/ahkpp#499]
### Description

Closing braces of arrays get moved to the next line.

### Expected formatted output snippet

```autohotkey
return [1, 0, 0]
```

### Actual formatted output snippet

```autohotkey
return [1, 0, 0
]
```

### Additional context

```autohotkey
foo := ["bar", "baz"
]
```

**Comment by mark-wiemer** [comment]
OK, I think I know the cause. Note to self: expose the hidden "preserve" option ;)
