### ISSUE TITLE
[v2] Standard Library Code Tips and Output

### ISSUE THREAD

**Issue by Mnjun** [mark-wiemer-org/ahkpp#500]
**Is your issue related to a problem? Please describe.**
I hope to add support for standard libraries, input prompts, and support for printing objects and arrays.  

**Describe the solution you'd like**
In VSCODE and AHK plugins, your plugin ranks first, but its support in this area is not as good as AutoHotkey v2 Language Support. We hope you can also add support for standard library prompts and printing functions. This is very convenient. Please
refer to the picture for details

He can encapsulate some JS methods, such as directly printing arrays, objects, using map functions=>
functions, etc. And there are input prompts and explanations for the standard library, which is very convenient. Please adopt it, it will be a great help to users. We can write AHK and print like writing JS. This is so wonderful

**Describe alternatives you've considered**

**Additional context**

![6ODFBQ9XG`~5GR$93J09)ZG](https://github.com/user-attachments/assets/38216101-5fb1-4550-a492-d4cf85f980e4)

**Comment by Mnjun** [comment]
I just tested it and found that in debug mode, it 
is indeed possible to output results. However, the
re is no input prompt for the standard version. Ca
n we consider adding this feature?
![Uploading image.png…]()

**Comment by Mnjun** [comment]
图片似乎上传失败了，我再发一下
![image](https://github.com/user-attachments/assets/35004c23-4d4d-4e05-9400-9ec01f375898)

**Comment by mark-wiemer** [comment]
Sorry, I'm not quite sure I understand the problem. Can you send two screenshots, one with the expected behavior and one with the current behavior? You can disable my extension and enable thqby's extension for comparison.

**Comment by mark-wiemer** [comment]
Completed in #549 for English, I won't be able to translate to other languages unfortunately
