### ISSUE TITLE
Processing of A_ScriptDir incorrect when used in macro directives (#Include) for v2

### ISSUE THREAD

**Issue by carlitorendon** [mark-wiemer-org/ahkpp#516]
## Code snippet

```
#Include "%A_ScriptDir%\common-functions.ahk2"
```

## Expected behavior

Assuming the file is in the same place where the script is, there should be no error. 

## Additional context
At present the highlighter is resolving the A_ScriptDir variable wrong. It seems to be placing it one level above where it should be and hence the error. 

![image](https://github.com/user-attachments/assets/5b6e19b4-d2a0-4248-a951-b561a154ea0c)

**Comment by mark-wiemer** [comment]
Please try the `F1 > Set A_ScriptDir Here` command with this file open and let me know if that helps. I'm still learning the code behind AHK v2 support, so I appreciate your patience :)

![image](https://github.com/user-attachments/assets/8bf17f94-7db3-46a7-8f39-578b34539dfa)

Please let me know if [thqby's extension](https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp) has the same issue, as my extension uses the code from that extension.

**Comment by carlitorendon** [comment]
Will give it a try and report back 👍

**Comment by carlitorendon** [comment]
So I gave it a try but that option is not displaying? See below: 

![image](https://github.com/user-attachments/assets/6a969942-b4d8-49f1-a05f-2a91a6a68992)

Now one detail I didn't mention at the beginning (didn't think it mattered) is I'm developing this via SSH onto a windows host. 
I went ahead and tried this on a host locally and it worked. 

So the question is, any reason you can think why this option would not be available when using in remote development?

**Comment by carlitorendon** [comment]
Another detail: I went ahead and remote desktop into the machine and there I did have the option. Set it and the error went away. 

When I connected my VS Code from another machine, the problem goes back to being there. So I think it may be something the extension is not handling related to remote development?

**Comment by mark-wiemer** [comment]
Yes, this probably doesn't work via SSH because the command requires the editor to see the current file as a "file", I'm sure via SSH it's something different. I may experiment with disabling this but I'd like to add a warning if the user is using SSH or some other "non-standard" method. There's nothing wrong with SSH, but I'm not sure if the current code would work without this condition.

Ref package.json:

https://github.com/mark-wiemer-org/ahkpp/blob/dc68ee25334b7195a90b9794ad8b65cc344c7891/package.json#L208

**Comment by carlitorendon** [comment]
That makes sense @mark-wiemer, I suppose my case is pretty niche. Thank you for this great extension.
