### ISSUE TITLE
"Go to Definition" broken for v1 scripts in 6.4.0

### ISSUE THREAD

**Issue by Lailloken** [mark-wiemer-org/ahkpp#559]
## Description

"Go to Definition" doesn't work anymore for v1 scripts in 6.4.0 and instead shows this:

![image](https://github.com/user-attachments/assets/cdeca869-e7f0-4747-8eaf-044a6348e982)

`No definition found for '__func_name__'`

The parameters of a function are displayed correctly when hovering over it, however:
![image](https://github.com/user-attachments/assets/f8057c1f-9779-47dd-9258-14945f5caf13)

Rolling back to 6.3.0 fixes the issue.

**Comment by mark-wiemer** [comment]
Sorry about this, this will be fixed in the next release for sure. Thanks for reporting.

**Comment by mark-wiemer** [comment]
Fix will be released this weekend, hoping to bundle another fix or two in there, plus I need to run a ton of manual tests every release to make sure I don't introduce new failures... like this one...

Thanks again for your patience, I hope you can see the new tests ensure this won't happen again!
