### ISSUE TITLE
go to defintion. not working

### ISSUE THREAD

**Issue by Doaexpert** [mark-wiemer-org/ahkpp#561]
## Description

go to definition is not working anymore with the latest updates

## Reproduction steps

gosub, definition
press f12, not working

## Expected behavior

open de ahk file where the definiton is.

## Additional context

Add any other context about the problem here, including screenshots. If no context is needed, please remove this section.

**Comment by mark-wiemer** [comment]
Dupe of #559, will be fixed in this weekend's release
