### ISSUE TITLE
Please support older VS Code versions

### ISSUE THREAD

**Issue by tycode** [mark-wiemer-org/ahkpp#574]
Hi!

I am stuck on VS Code v1.91.x due to https://github.com/microsoft/vscode/issues/224515. MS doesn't seem to be in a hurry to resolve this, so I expect this to remain the case for the foreseeable future.

So my VS Code will not install ahkpp newer than 6.1.1.

I noticed this extension bumped the required VS Code version from 1.90.x to 1.93.x in c3adca48... which claims to be #527... which provides no further context but I assume it's talking about merging the functionality from [thqby/vscode-autohotkey2-lsp](https://github.com/thqby/vscode-autohotkey2-lsp).

Yet that repo's package.json, atow, only requires VS Code 1.82.0, [as seen here](https://github.com/thqby/vscode-autohotkey2-lsp/blob/f21d7d76a13a12ba94589e9c703506249ce3a4e6/package.json#L30).

My guess is that your bump wasn't actually necessary - if it's just a case of changing the number back and submitting a patch release to the marketplace, can you please do so?

FWIW, I'm here due to #493. I'm on Linux using [AHK_X11](https://github.com/phil294/AHK_X11), so AHK2 is irrelevant to me and what I'm really after is to get rid of the "select interpreter" popup. Funnily enough, ahkpp actually misinterprets some of my (very small) AHK1 scripts as AHK2 scripts; if there's a way to tell it I only want AHK1 support in general, that'd be pretty fantastic, too.

**Comment by mark-wiemer** [comment]
Hi, I'll see what I can do. As I'm away from vacation, I suggest you install the latest version 5.x in the short term to get rid of that popup. Sorry for the inconvenience. Ref https://github.com/mark-wiemer-org/ahkpp/blob/main/docs/Troubleshooting.md#install-specific-version-of-ahk

**Comment by tycode** [comment]
Thanks, I can confirm installing 5.0.7 (the latest 5.x that showed for me) does indeed get rid of the popup.

Sadly VS Code then displays a badge complaining that I have extensions that could be updated, which is more distracting than the popup... so I'll stick to the latest version for now. (It really should not count manually-downgraded extensions towards the number of updatable extensions, imo - this is definitely not your issue, though. I might raise this upstream some day...)

The popup really isn't any trouble for me so don't worry about that. I raised this issue proactively from the POV of "version requirements shouldn't be bumped for no reason" rather than anything else (and if there is a good reason, i.e. "requires this new feature", then documenting that in the release notes or commit message etc. would have been fine). I'm in no rush. :)

**Comment by mark-wiemer** [comment]
You are right. I remember wanting a new feature, but I can re-evaluate. Just give me another week ;)

**Comment by mark-wiemer** [comment]
Reducing the requirements back down to VS Code 1.68 :)
