### ISSUE TITLE
Open related AHK documentation/help

### ISSUE THREAD

**Issue by tdalon** [mark-wiemer-org/ahkpp#78]
I am looking for a feature to quickly open the documentation page related to the current function or command used in the current editor window. 

A hotkey taking for example the function name at cursor location or function used in the current line.

**Comment by fade2gray** [comment]
I use this script when necessary...

```ahk
; Make sure command has been copied to the clipboard and run this script
Loop, Files,% "C:\Users\" A_UserName "\.vscode\extensions\*", D
    if InStr(A_LoopFilePath, "mark-wiemer.vscode-autohotkey-plus-plus"){
        file := A_LoopFilePath "\snippets\ahk.json"
        Break
    }
FileRead, snippets, %file%
If !InStr(snippets, Clipboard){
    MsgBox, Invalid command.
    ExitApp
}
Run,% "https://www.autohotkey.com/docs/commands/" Clipboard ".htm"
```

**Comment by tdalon** [comment]
Thanks fade2gray. I have come finally to use your approach. See details [here](https://tdalon.blogspot.com/2021/04/ahk-vscode-help.html) for a bit more optimized implementation.

**Comment by mark-wiemer** [comment]
Another approach: a "context-sensitive help" script written in AHK: [Script Showcase | AutoHotkey](https://www.autohotkey.com/docs/scripts/#ContextSensitiveHelp)

**Comment by FuPeiJiang** [comment]
@fade2gray thank you, I have been using your script until now, I really like how it redirects you to the correct page: `"https://www.autohotkey.com/docs/commands/" Clipboard ".htm"`
for example: https://www.autohotkey.com/docs/commands/==.htm redirecting you to https://www.autohotkey.com/docs/Variables.htm#equal

how did you find this ? that www.autohotkey.com/docs/commands/ will redirect you
@mark-wiemer thank you, imo this offline version is best, it's also the version of ahk you are using

(I've had issues with using a newer documentation than the AutoHotkey.exe I have installed)

**Comment by mark-wiemer** [comment]
Closing this as there is a suitable alternative and no easy way to implement within the extension itself. As always, happy to consider any insights, but I do need to keep the backlog clean :)

**Comment by kyklish** [comment]
[`AHK-Studio` implementation](https://github.com/maestrith/AHK-Studio/blob/811414395ae4f9778a3aad756c6b156651954f52/AHK-Studio.ahk#L5048).

**Comment by kyklish** [comment]
Just test it. `Internet Explorer` opens `chm` file just fine.

**Comment by mark-wiemer** [comment]
See also [docs for HTML help executable](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/about-the-html-help-executable-program) (hh.exe)

**Comment by mark-wiemer** [comment]
@kyklish and anyone else looking into this: I'm seeing a lot of Internet Explorer in the code that does work. But I won't accept an Internet Explorer-based solution simply because IE is extremely deprecated. Please try to find a workaround that uses the native `hh.exe` or even opens the corresponding search page in the user's default browser.

**Comment by mark-wiemer** [comment]
Win+R with `hh.exe "C:\Program Files\AutoHotkey\AutoHotkey.chm::/docs/Tutorial.htm"` may be what we've been looking for, found via some experimentation and referencing [official docs](https://learn.microsoft.com/en-us/previous-versions/office/developer/office-xp/aa164814(v=office.10))

**Comment by mark-wiemer** [comment]
Unfortunately it looks like we'd need to know all the URLs in advance and map them to certain selections (e.g. map "Gui" to "/docs/commands/Gui.htm"). However, there's no easy way to get all the URLs as they don't follow a perfect naming scheme.

If there were an easy way to interact with the `.chm` file in JavaScript to paste a search and choose the first result, that'd be neat. Currently [AHK-Studio](https://github.com/maestrith/AHK-Studio/blob/811414395ae4f9778a3aad756c6b156651954f52/AHK-Studio.ahk#L5068-L5103) is using some fancy regular expressions to deduce the URLs, so if we could copy this logic into TypeScript we'd be golden.

**Comment by mark-wiemer** [comment]
I did try to [decompile the help file](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/decompiling-a-help-file), but nothing seemed to happen. We could find the source docs from the repo itself, probably.

**Comment by kyklish** [comment]
> Unfortunately it looks like we'd need to know all the URLs in advance and map them to certain selections (e.g. map "Gui" to "/docs/commands/Gui.htm"). However, there's no easy way to get all the URLs.

I found such list of URLs in other AHK related project. I will post link to it later.

**Comment by mark-wiemer** [comment]
Working on this issue in the https://github.com/vscode-autohotkey/ahkpp/tree/help-page branch

**Comment by CoffeeChaton** [comment]
> > Unfortunately it looks like we'd need to know all the 
URLs in advance and map them to certain selections (e.g. map "Gui" to "/docs/commands/Gui.htm"). However, there's no easy way to get all the URLs.
> 
> I found such list of URLs in other AHK related project. I will post link to it later.

- offline help
  1. `C:\Program Files\AutoHotkey\AutoHotkey.chm`
  2. using 7z.exe unzip `AutoHotkey.chm`
  ![2023-03-13_21-06-23](https://user-images.githubusercontent.com/63182963/224710365-04ad6e67-1881-43ae-8d17-d1faa4a82959.png)

- online help, just need to open https://github.com/AutoHotkey/AutoHotkeyDocs/tree/v1

Remark: after this pr <https://github.com/AutoHotkey/AutoHotkeyDocs/pull/596>\
The latest *offline help* file has a very different path from the *online help*

**Comment by kyklish** [comment]
[URLs to documentation](https://github.com/TheArkive/CallTipsForAll/tree/master/Languages/AHK1)

**Comment by mark-wiemer** [comment]
Should be possible to copy [thqby's quick help code](https://github.com/thqby/vscode-autohotkey2-lsp/blob/fa0782e8a221e54e5755358eb594ae9cc872ca1a/client/src/extension.ts#L348), the only concern is writing tests for it and ensuring that it's fit for purpose. Not a priority currently as I continue work towards v2 support.
