### ISSUE TITLE
Add option to disable syntax highlighting

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer-org/ahkpp#84]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting in this extension isn't good, but many other features are. I want to combine this extension with another, but they clash on syntax highlighting so I can't.

**Describe the solution you'd like**
Ideally I can disable syntax highlighting from this extension, and enable another extension specifically for syntax highlighting. That way, I can have great syntax highlighting plus all the other features of AHK++.

Bonus: Just fix the syntax highlighting of AHK++ ;)

**Describe alternatives you've considered**
Trying to enable and disable extensions as needed is possible, but very clunky.

**Additional context**
See [Use this extension along with "AutoHotKey2 Language Support" by thqby for syntax error highlighting · Discussion #75 · mark-wiemer/vscode-autohotkey-plus-plus](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/discussions/75)

**Comment by mark-wiemer** [comment]
Closing this as the discussion that started it (#75) didn't want this extension to be disabled, but wanted this extension to take priority over another.

If anyone wants this feature, feel free to open a new issue or comment here asking me to re-open this one :)

**Comment by alfredomtx** [comment]
> comment here asking me to re-open this one :)

I would love to have this option, I also found another extension with better highlighting(https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp) and unfortunately ahkpp takes precedence over this one :/

**Comment by alfredomtx** [comment]
@mark-wiemer 

> comment here asking me to re-open this one :)

I would love to have this option, I also found another extension with better highlighting(https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp) and unfortunately ahkpp takes precedence over this one :/

**Comment by mark-wiemer** [comment]
Not closing, but deprioritizing this one as I look at other's with more impact. Please let me know what syntax highlighting issues are most pressing -- NekoHelp is licensed under LGPL so I should be able to copy-paste any code from there to improve this project :)

**Comment by mark-wiemer** [comment]
Closing as low priority. I may come back to this, but it's very hard to make this extension toggle syntax highlighting, and the best approach I can think of is offering a non-highlighting version, but that would be awkward. Ultimately I'd recommend folks to let me know where the highlighting is lacking so I can improve AHK++ itself :)
