### ISSUE TITLE
Support for AHK V2 syntax

### ISSUE THREAD

**Issue by gamagan** [mark-wiemer-org/ahkpp#96]
Does this extension support AHK V2 syntax, or is it only V1?
It doesn't seem to support it; the colors get messed up for V2 scripts.

**Comment by itsmeboy0** [comment]
You could use this for now:
https://github.com/thqby/vscode-autohotkey2-lsp

**Comment by mark-wiemer** [comment]
AHK v2 recently became stable. I will strongly consider adding support when I have more time to work on this project. Step 1 is finding the parsing logic in the language definition and copying that. This will provide a solid foundation for formatting, syntax highlighting, and IntelliSense.

**Comment by mark-wiemer** [comment]
See #123

**Comment by mark-wiemer** [comment]
See #146

**Comment by mark-wiemer** [comment]
With AHK v2 being fully released, this is now top priority :)

**Comment by JroachAu** [comment]
I'm not sure if its related to v2, but I just installed V2, and now when I'm trying to run my script, I am getting:
```
'"C:\Program Files\AutoHotkey\v2\AutoHotkeyU64.exe"' is not recognized as an internal or external command,
operable program or batch file.
```
By default, '/' was used in the extension settings which gave the same error, so then I swapped to '\' whereby the help file is accessible, but still the error above occurs.

**Comment by mark-wiemer** [comment]
@JroachAu , your issue is unrelated to this one 😕 you're welcome to create a new discussion to help get setup, I'm not sure this is an issue with this extension. Double-check your file path, I've gotten v2 working on my machine so I know it can be done!

**Comment by mark-wiemer** [comment]
Refer to progress in https://github.com/mark-wiemer/hello-vscode-extension for my WIP prototypes. I would love to understand https://github.com/thqby/vscode-autohotkey2-lsp and other repos in https://github.com/stars/mark-wiemer/lists/syntax-highlighting so I don't reinvent the wheel. This will take some time, but it remains interesting work and my schedule is finally a bit clearer.

**Comment by mark-wiemer** [comment]
I'm still looking at this every once in a while, but I've mostly dedicated my free time to other projects. I'll be writing code related to this within the month, at least. As always, this is a passion project so please be patient :)

**Comment by jkyeung** [comment]
Cheers to the new release!

This probably removes the last excuse I have for not switching to v2.

Let's be honest: There's a pretty good chance there are bugs in the v2 support, and there's even a chance some v1 support has been broken. That's OK. That's normal for a major release. It's still an incredible milestone, and you have my full congratulations!

And thanks again just for the existence of this project. It is indeed a great tool.

**Comment by mark-wiemer** [comment]
I really hope nothing with V1 broke! I promise I tested things as thoroughly as I could, all basic scenarios should be working just fine. Please do report issues if you see them! I'm aware of four issues with V2 support, nothing critical though. Fixes and enhancements will continue for the foreseeable future 🤓

Thank you for the kind words!
